// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

import { request } from "@/utils/request";
import type { CreateAccountRequest, CreateAccountResponse, DeleteAccountRequest, DeleteAccountResponse, EnabledAccountRequest, EnabledAccountResponse, ListAccountRequest, ListAccountResponse, ResetPasswordRequest, ResetPasswordResponse, SendCodeRequest, SendCodeResponse, SetAuthorityRequest, SetAuthorityResponse, VerifyCodeRequest, VerifyCodeResponse } from "./account.type";

/** account module apis */
export const accountApi = {
  /** 注册/修改管理员账号 */
  createAccountHandler: (data?: CreateAccountRequest) => request.post<CreateAccountResponse>("/admin/account/create", data),

  /** 删除管理员账号 */
  deleteAccountHandler: (data?: DeleteAccountRequest) => request.post<DeleteAccountResponse>("/admin/account/delete", data),

  /** 启用/禁用管理员账号 */
  enabledAccountHandler: (data?: EnabledAccountRequest) => request.post<EnabledAccountResponse>("/admin/account/enabled", data),

  /** 获取管理员账号列表 */
  listAccountHandler: (data?: ListAccountRequest) => request.post<ListAccountResponse>("/admin/account/list", data),

  /** 重置密码 */
  resetPasswordHandler: (data?: ResetPasswordRequest) => request.post<ResetPasswordResponse>("/admin/account/reset-password", data),

  /** 绑定邮箱/找回密码 */
  sendCodeHandler: (data?: SendCodeRequest) => request.post<SendCodeResponse>("/admin/account/send-code", data),

  /** 设置权限 */
  setAuthorityHandler: (data?: SetAuthorityRequest) => request.post<SetAuthorityResponse>("/admin/account/setAuthority", data),

  /** 校验绑定验证码/校验并修改密码 */
  verifyCodeHandler: (data?: VerifyCodeRequest) => request.post<VerifyCodeResponse>("/admin/account/verify-code", data),
};
