// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

/** AccountInfo */
export interface AccountInfo {
  /** 账号名 */
  account: string;
  /** 备注 */
  desc?: string;
  /** 邮箱 */
  email?: string;
  /** 是否启用 */
  enabled: boolean;
  /** 数据库记录 ID */
  id: number;
  /** 是否超级管理员 */
  isSuper: boolean;
  /** 昵称（创建账号时必填） */
  nickname?: string;
  /** 最后修改者 */
  operator: string;
  /** 密码明文（创建账号时必填） */
  password?: string;
  /** 手机号 */
  phone?: string;
  /** 真名 */
  realname?: string;
  /** 关联用户组列表 */
  roles: RoleInfo[];
  /** 最后修改时间 */
  updateTime: string;
}

/** CreateAccountRequest */
export interface CreateAccountRequest {
  /** 账号名 */
  account: string;
  /** 备注 */
  desc?: string;
  /** 邮箱 */
  email?: string;
  /** 是否启用 */
  enabled?: boolean;
  /** 数据库记录 ID，创建时为 0，修改时必填 */
  id?: number;
  /** 昵称（创建账号时必填） */
  nickname?: string;
  /** 密码明文（创建账号时必填） */
  password?: string;
  /** 手机号 */
  phone?: string;
  /** 真名 */
  realname?: string;
}

/** CreateAccountRes */
export interface CreateAccountRes {
  /** 账号 ID */
  accountId: number;
}

/** CreateAccountResponse */
export interface CreateAccountResponse {
  /** 错误码 */
  code?: number;
  data?: CreateAccountRes;
  /** 错误信息 */
  msg?: string;
}

/** DeleteAccountRequest */
export interface DeleteAccountRequest {
  /** 数据库记录 ID 列表 */
  accountIds: number[];
}

/** DeleteAccountResponse */
export interface DeleteAccountResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** EnabledAccountRequest */
export interface EnabledAccountRequest {
  /** 账号 ID 列表 */
  accountIds: number[];
  /** 是否启用 */
  enabled: boolean;
}

/** EnabledAccountResponse */
export interface EnabledAccountResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** ListAccountRequest */
export interface ListAccountRequest {
  /** 筛选账号或昵称 */
  name?: string;
  /** 页码，从 1 开始 */
  page?: number;
  /** 每页数量 */
  pageSize?: number;
}

/** ListAccountRes */
export interface ListAccountRes {
  /** 列表数据 */
  items: AccountInfo[];
  /** 避免全表扫描，此字段数值总是 page * pageSize + 1 */
  total?: number;
}

/** ListAccountResponse */
export interface ListAccountResponse {
  /** 错误码 */
  code?: number;
  data?: ListAccountRes;
  /** 错误信息 */
  msg?: string;
}

/** MenuInfo */
export interface MenuInfo {
  /** 图标 */
  icon: string;
  /** 数据库记录 ID */
  id: number;
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 上级菜单 ID */
  parentId: number;
  /** 排序 */
  rank: number;
  /** 路由 */
  route: string;
  /** 最后修改时间 */
  updateTime?: string;
}

/** ResetPasswordRequest */
export interface ResetPasswordRequest {
  /** 要修改的账号名（非超管修改自己密码时不要填） */
  account?: string;
  /** 新密码 */
  newPassword: string;
  /** 旧密码（非超管必填） */
  oldPassword?: string;
}

/** ResetPasswordResponse */
export interface ResetPasswordResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** RoleInfo */
export interface RoleInfo {
  /** 描述 */
  desc: string;
  /** 数据库记录 ID */
  id: number;
  /** 关联菜单列表 */
  menus: MenuInfo[];
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 最后修改时间 */
  updateTime?: string;
}

/** SendCodeRequest */
export interface SendCodeRequest {
  /** 要绑定的邮箱 */
  email: string;
  /** 发送验证码的原因：1-绑定邮箱，2-找回密码 */
  reason: number;
}

/** SendCodeResponse */
export interface SendCodeResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** SetAuthorityRequest */
export interface SetAuthorityRequest {
  /** 账号 ID 列表 */
  accountIds: number[];
  /** 用户组 ID 列表 */
  roleIds?: number[];
}

/** SetAuthorityResponse */
export interface SetAuthorityResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** VerifyCodeRequest */
export interface VerifyCodeRequest {
  /** 验证码 */
  code: string;
  /** 要绑定的邮箱/账号绑定的邮箱 */
  email: string;
  /** 新密码（修改密码时必填） */
  newPassword?: string;
}

/** VerifyCodeResponse */
export interface VerifyCodeResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}
