// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

// Re-export apis by module

export { accountApi } from "./account";
export { logApi } from "./log";
export { loginApi } from "./login";
export { menuApi } from "./menu";
export { roleApi } from "./role";
