// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

import { request } from "@/utils/request";
import type { AdminLogRequest, AdminLogResponse } from "./log.type";

/** log module apis */
export const logApi = {
  /** 获取后台操作日志 */
  listAdminLogHandler: (data?: AdminLogRequest) => request.post<AdminLogResponse>("/admin/log/list", data),
};
