// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

/** AdminLogItem */
export interface AdminLogItem {
  /** 筛选管理员账号名 */
  account: string;
  /** 操作管理员 ID */
  adminId: number;
  /** 操作时间 */
  createTime: string;
  /** 日志 ID */
  id: number;
  /** 操作请求 IP 地址 */
  ip: string;
  /** 操作请求体 */
  reqBody: string;
  /** 操作请求路由地址 */
  reqRoute: string;
  /** 操作响应体 */
  resBody: string;
  /** 操作请求头部 UA 字段 */
  userAgent: string;
}

/** AdminLogRequest */
export interface AdminLogRequest {
  /** 筛选管理员账号名 */
  account?: string;
  /** 筛选管理员 ID */
  accountId?: number;
  /** 筛选操作结束时间 */
  endTime: string;
  /** 筛选 IP */
  ip?: string;
  /** 页码，从 1 开始 */
  page?: number;
  /** 每页数量 */
  pageSize?: number;
  /** 筛选操作路由 */
  reqRoute?: string;
  /** 筛选操作起始时间 */
  startTime: string;
}

/** AdminLogRes */
export interface AdminLogRes {
  /** 列表数据 */
  items: AdminLogItem[];
  /** 避免全表扫描，此字段数值总是 page * pageSize + 1 */
  total?: number;
}

/** AdminLogResponse */
export interface AdminLogResponse {
  /** 错误码 */
  code?: number;
  data?: AdminLogRes;
  /** 错误信息 */
  msg?: string;
}
