// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

import { request } from "@/utils/request";
import type { LoginRequest, LoginResponse, LogoutResponse } from "./login.type";

/** login module apis */
export const loginApi = {
  /** 后台登录 */
  loginHandler: (data?: LoginRequest) => request.post<LoginResponse>("/admin/login", data),

  /** 后台登出 */
  logoutHandler: () => request.post<LogoutResponse>("/admin/logout"),
};
