// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

/** LoginRequest */
export interface LoginRequest {
  /** 账号名 */
  account: string;
  /** 密码 */
  password: string;
}

/** LoginRes */
export interface LoginRes {
  /** 账号 ID */
  accountId: number;
  /** 账号名 */
  accountName: string;
  /** 是否已绑定 EMAIL */
  isBoundEMail: boolean;
  /** 是否超级管理员 */
  isSuper: boolean;
  /** JWT */
  jwtToken: string;
  /** 账号所属用户组列表 */
  roles: RoleInfo[];
}

/** LoginResponse */
export interface LoginResponse {
  /** 错误码 */
  code?: number;
  data?: LoginRes;
  /** 错误信息 */
  msg?: string;
}

/** LogoutResponse */
export interface LogoutResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** MenuInfo */
export interface MenuInfo {
  /** 图标 */
  icon: string;
  /** 数据库记录 ID */
  id: number;
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 上级菜单 ID */
  parentId: number;
  /** 排序 */
  rank: number;
  /** 路由 */
  route: string;
  /** 最后修改时间 */
  updateTime?: string;
}

/** RoleInfo */
export interface RoleInfo {
  /** 描述 */
  desc: string;
  /** 数据库记录 ID */
  id: number;
  /** 关联菜单列表 */
  menus: MenuInfo[];
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 最后修改时间 */
  updateTime?: string;
}
