// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

import { request } from "@/utils/request";
import type { CreateMenuRequest, CreateMenuResponse, DeleteMenuRequest, DeleteMenuResponse, ListMenuRequest, ListMenuResponse } from "./menu.type";

/** menu module apis */
export const menuApi = {
  /** 创建/修改菜单 */
  createMenuHandler: (data?: CreateMenuRequest) => request.post<CreateMenuResponse>("/admin/menu/create", data),

  /** 删除菜单 */
  deleteMenuHandler: (data?: DeleteMenuRequest) => request.post<DeleteMenuResponse>("/admin/menu/delete", data),

  /** 获取菜单列表 */
  listMenuHandler: (data?: ListMenuRequest) => request.post<ListMenuResponse>("/admin/menu/list", data),
};
