// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

/** CreateMenuRequest */
export interface CreateMenuRequest {
  /** 图标 */
  icon?: string;
  /** 数据库记录 ID，创建时为 0，修改时必填 */
  id?: number;
  /** 名称 */
  name: string;
  /** 上级菜单 ID */
  parentId?: number;
  /** 排序 */
  rank: number;
  /** 路由 */
  route: string;
}

/** CreateMenuRes */
export interface CreateMenuRes {
  /** 数据库记录 ID */
  id: number;
}

/** CreateMenuResponse */
export interface CreateMenuResponse {
  /** 错误码 */
  code?: number;
  data?: CreateMenuRes;
  /** 错误信息 */
  msg?: string;
}

/** DeleteMenuRequest */
export interface DeleteMenuRequest {
  /** 数据库记录 ID */
  id: number;
}

/** DeleteMenuResponse */
export interface DeleteMenuResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** ListMenuRequest */
export interface ListMenuRequest {
  /** 页码，从 1 开始 */
  page?: number;
  /** 每页数量 */
  pageSize?: number;
}

/** ListMenuRes */
export interface ListMenuRes {
  /** 列表数据 */
  items: MenuInfo[];
  /** 避免全表扫描，此字段数值总是 page * pageSize + 1 */
  total?: number;
}

/** ListMenuResponse */
export interface ListMenuResponse {
  /** 错误码 */
  code?: number;
  data?: ListMenuRes;
  /** 错误信息 */
  msg?: string;
}

/** MenuInfo */
export interface MenuInfo {
  /** 图标 */
  icon: string;
  /** 数据库记录 ID */
  id: number;
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 上级菜单 ID */
  parentId: number;
  /** 排序 */
  rank: number;
  /** 路由 */
  route: string;
  /** 最后修改时间 */
  updateTime?: string;
}
