// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

import { request } from "@/utils/request";
import type { CreateRoleRequest, CreateRoleResponse, DeleteRoleRequest, DeleteRoleResponse, ListRoleRequest, ListRoleResponse } from "./role.type";

/** role module apis */
export const roleApi = {
  /** 创建/修改用户组 */
  createRoleHandler: (data?: CreateRoleRequest) => request.post<CreateRoleResponse>("/admin/role/create", data),

  /** 删除用户组 */
  deleteRoleHandler: (data?: DeleteRoleRequest) => request.post<DeleteRoleResponse>("/admin/role/delete", data),

  /** 获取用户组列表 */
  listRoleHandler: (data?: ListRoleRequest) => request.post<ListRoleResponse>("/admin/role/list", data),
};
