// AUTO-GENERATED BY scripts/generate-apis-from-swagger.mjs. DO NOT EDIT.

/** CreateRoleRequest */
export interface CreateRoleRequest {
  /** 描述 */
  desc?: string;
  /** 数据库记录 ID，创建时为 0，修改时必填 */
  id?: number;
  /** 菜单 ID 列表 */
  menuIds: number[];
  /** 名称 */
  name: string;
}

/** CreateRoleRes */
export interface CreateRoleRes {
  /** 数据库记录 ID */
  id: number;
}

/** CreateRoleResponse */
export interface CreateRoleResponse {
  /** 错误码 */
  code?: number;
  data?: CreateRoleRes;
  /** 错误信息 */
  msg?: string;
}

/** DeleteRoleRequest */
export interface DeleteRoleRequest {
  /** 数据库记录 ID */
  id: number;
}

/** DeleteRoleResponse */
export interface DeleteRoleResponse {
  /** 错误码 */
  code?: number;
  /** 错误信息 */
  msg?: string;
}

/** ListRoleRequest */
export interface ListRoleRequest {
  /** 筛选名称 */
  name?: string;
  /** 页码，从 1 开始 */
  page?: number;
  /** 每页数量 */
  pageSize?: number;
}

/** ListRoleRes */
export interface ListRoleRes {
  /** 列表数据 */
  items: RoleInfo[];
  /** 避免全表扫描，此字段数值总是 page * pageSize + 1 */
  total?: number;
}

/** ListRoleResponse */
export interface ListRoleResponse {
  /** 错误码 */
  code?: number;
  data?: ListRoleRes;
  /** 错误信息 */
  msg?: string;
}

/** MenuInfo */
export interface MenuInfo {
  /** 图标 */
  icon: string;
  /** 数据库记录 ID */
  id: number;
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 上级菜单 ID */
  parentId: number;
  /** 排序 */
  rank: number;
  /** 路由 */
  route: string;
  /** 最后修改时间 */
  updateTime?: string;
}

/** RoleInfo */
export interface RoleInfo {
  /** 描述 */
  desc: string;
  /** 数据库记录 ID */
  id: number;
  /** 关联菜单列表 */
  menus: MenuInfo[];
  /** 名称 */
  name: string;
  /** 最后修改者 */
  operator?: string;
  /** 最后修改时间 */
  updateTime?: string;
}
